---
galaxy_info:
  role_name: golang
  description: Install Go toolchain, environment, and protoc-gen-go
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions: [bookworm, jammy, noble]
    - name: EL
      versions: [8, 9]
    - name: MacOSX
      versions: [all]

dependencies:
  - role: common
