---
_shellcheck_pkg: shellcheck
_yamllint_pkg: yamllint
_universal_ctags_pkg: universal-ctags
_ansible_lint_pkg: ansible-lint
_actionlint_pkg: actionlint
_nodejs_pkg: node
_npm_global_bin: /usr/local/bin
_cppcheck_pkg: cppcheck
_clang_tidy_pkg: llvm
_ruff_pkg: ruff
